[package]
name = "nanodb-server-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
nanodb-core = { path = "../core" }
tokio = { version = "1.0", features = ["full"] }
tonic = "0.14.2"
prost = "0.14.1"
prost-types = "0.14.1"

[build-dependencies]
tonic-build = "0.14.2"
prost-build = "0.14.1"