[package]
name = "nanodb-server-tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
nanodb-core = { path = "../core" }
tokio = { workspace = true }
serde = { workspace = true }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
bytes = "1.0"